# #index:
# #    path: /
# #    controller: App\Controller\DefaultController::index
# lucky_number:
#     path: /lucky/number
#     controller: App\Controller\LuckyController::number
# hello_world:
#     path: /hello/world
#     controller: App\Controller\HelloController::hello